"""Generate fictitious participants, microbes and publication records from scratch."""
from pathlib import Path
import json
import numpy as np
import pandas as pd


def generate_synthetic(output: Path, seed: int = 17) -> None:
    output = Path(output)
    if output.exists() and any(output.iterdir()):
        raise ValueError("Output directory is not empty; choose a new directory")
    rng = np.random.default_rng(seed)
    genera = [f"Genus{chr(65 + i)}" for i in range(8)]
    metadata, abundances = [], []
    for source in ["SyntheticSourceA", "SyntheticSourceB"]:
        groups = [("ReferenceOnly", "control", "", 180)]
        for study in ["StudyA", "StudyB"]:
            groups += [(study, "control", "", 24), (study, "case", "SyntheticConditionA", 12),
                       (study, "case", "SyntheticConditionB", 12)]
        for study, group, disease, n in groups:
            for _ in range(n):
                sample = f"synthetic-sample-{len(metadata) + 1:04d}"
                a = rng.lognormal(mean=-.2, sigma=.75, size=len(genera))
                a[rng.random(len(genera)) < .08] = 0
                if group == "case":
                    # Mixed examples: literature-aligned, opposed and unchanged genera.
                    a *= [2.6, .35, .4, 1.8, 1, 1, 1, 1] if disease.endswith("A") else [.5, 2.2, 1.2, .7, 1, 1, 1, 1]
                a[6] = 0  # Always undetected; falls back to [0, 1e-6].
                a[7] = 1  # Equal positive bounds; low takes precedence.
                if a.sum() > 90:
                    a *= 90 / a.sum()
                metadata.append(dict(sample_id=sample, source=source, study_id=study,
                                     group=group, disease=disease))
                abundances.append(dict(sample_id=sample, **dict(zip(genera, a))))
    records = []
    for dindex, disease in enumerate(["SyntheticConditionA", "SyntheticConditionB"]):
        directions = [1, -1, 1, -1, 1, 0, 1, -1] if dindex == 0 else [-1, 1, -1, 1, -1, 0, 1, -1]
        for j, (genus, sign) in enumerate(zip(genera, directions)):
            if j == 5:  # Explicitly absent literature relation.
                continue
            for paper_index in range(3):
                publication = f"synthetic-paper-{dindex}-{j}-{paper_index}"
                # Repeated extraction records do not give this publication extra votes.
                for repeat in range(3 if paper_index == 0 else 1):
                    records.append(dict(record_id=f"synthetic-record-{len(records) + 1:04d}",
                        disease=disease, genus=genus, publication_id=publication, direction=sign))
    output.mkdir(parents=True, exist_ok=True)
    pd.DataFrame(metadata).to_csv(output / "participants.csv", index=False)
    pd.DataFrame(abundances).to_csv(output / "abundance.csv", index=False)
    pd.DataFrame(records).to_csv(output / "votes.csv", index=False)
    pd.DataFrame({"publication_id": ["synthetic-paper-0-0-2"]}).to_csv(output / "exclusions.csv", index=False)
    (output / "SYNTHETIC_DATA_NOTICE.json").write_text(json.dumps({
        "synthetic": True, "seed": seed,
        "description": "Entirely invented samples, sources, diseases, microbes and publications; generated by source code in this repository. No manuscript data or results.",
        "sample_count": len(metadata), "genus_count": len(genera),
        "percentage_points": True}, indent=2) + "\n", encoding="utf-8")
